# Generated by Django 5.0.3 on 2024-03-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Educador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('educandos', models.ManyToManyField(related_name='educador', to='Cliente.educando')),
            ],
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
                ('arquivo', models.FileField(unique=True, upload_to='')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.educando')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('conteudo', models.TextField(max_length=300)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.educando')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.educador')),
            ],
        ),
    ]
