# Generated by Django 5.0.3 on 2024-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
