# Generated by Django 5.0.3 on 2024-04-30 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotações',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='data_de_publicacao')),
                ('concentracao', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('engajamento', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('competencias_tecnicas', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('competencias_socio_emocionais', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('observacoes', models.TextField()),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ('-data_de_publicacao',),
            },
        ),
    ]
