# Generated by Django 5.0.3 on 2024-04-30 20:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_anotações'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='data_de_publicacao')),
                ('concentracao', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('engajamento', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('competencias_tecnicas', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('competencias_socio_emocionais', models.CharField(choices=[('Ruim', 'Ruim'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='Excelente', max_length=15)),
                ('observacoes', models.TextField()),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ('-data_de_publicacao',),
            },
        ),
        migrations.DeleteModel(
            name='Anotações',
        ),
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
