# Generated by Django 5.0.3 on 2024-05-07 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_anotacoes_delete_anotações_delete_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='dia',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
        ),
        migrations.AddField(
            model_name='turma',
            name='horario',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anotacoes',
            name='remetente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
    ]
