# Generated by Django 5.0.3 on 2024-05-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_turma_alunos_turma_quantidade_maxima_alunos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.CharField(default='Musicalização infantil', max_length=30),
        ),
    ]
