# Generated by Django 5.0.3 on 2024-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_turma_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='is_enviado',
            field=models.BooleanField(default=False, verbose_name='enviado'),
        ),
    ]
