# Generated by Django 5.0.3 on 2024-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_boleto_is_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
