# Generated by Django 5.0.3 on 2024-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_boleto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
