# Generated by Django 5.0.3 on 2024-05-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_boleto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='is_enviado',
        ),
    ]
