# Generated by Django 5.0.6 on 2024-06-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_remove_boleto_is_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_deleted',
            field=models.DateField(blank=True, null=True, verbose_name='date_deleted'),
        ),
    ]
